### PR TITLE
Added back button capability

### PR DESCRIPTION
**Pull request by YeahButHats**
This was just really bothering me so I had to fix it. It works (from what I can tell) from the about page, recall alerts, and details overlay

### CODE REVIEW

**Comment by jackcompton** [comment]
this is cool, but it breaks the "about" link on the detail screen, (and maybe others?).

**Comment by iyameen** [comment]
I thought we are on a code freeze? @jackcompton @venka10 

I can appreciate the back button support being a bug.

**Comment by jackcompton** [comment]
I'm not sure everyone is aware we are in code freeze. Nothing has been merged since last night though, so don't worry yet.

**Comment by michellemas** [comment]
This has not been tested. I'm assuming this is not going to be in the product as of now.

**Pull request closed without merging**
